// SPDX-License-Identifier: Apache-2.0
//go:build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *RuneBenchmark) DeepCopyInto(out *RuneBenchmark) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RuneBenchmarkSpec) DeepCopyInto(out *RuneBenchmarkSpec) {
	*out = *in
	in.Budget.DeepCopyInto(&out.Budget)
}

func (in *Budget) DeepCopyInto(out *Budget) {
	*out = *in
	if in.MaxCostUSD != nil {
		inQ, outQ := &in.MaxCostUSD, &out.MaxCostUSD
		*outQ = new(resource.Quantity)
		**outQ = **inQ
	}
}

func (in *RuneBenchmark) DeepCopy() *RuneBenchmark {
	if in == nil {
		return nil
	}
	out := new(RuneBenchmark)
	in.DeepCopyInto(out)
	return out
}

func (in *RuneBenchmark) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RuneBenchmarkList) DeepCopyInto(out *RuneBenchmarkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuneBenchmark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RuneBenchmarkList) DeepCopy() *RuneBenchmarkList {
	if in == nil {
		return nil
	}
	out := new(RuneBenchmarkList)
	in.DeepCopyInto(out)
	return out
}

func (in *RuneBenchmarkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RuneBenchmarkStatus) DeepCopyInto(out *RuneBenchmarkStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	in.LastRun.DeepCopyInto(&out.LastRun)
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]RunRecord, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RunRecord) DeepCopyInto(out *RunRecord) {
	*out = *in
	in.SubmittedAt.DeepCopyInto(&out.SubmittedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}
