// SPDX-License-Identifier: Apache-2.0
//go:build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *RuneBenchmark) DeepCopyInto(out *RuneBenchmark) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RuneBenchmark) DeepCopy() *RuneBenchmark {
	if in == nil {
		return nil
	}
	out := new(RuneBenchmark)
	in.DeepCopyInto(out)
	return out
}

func (in *RuneBenchmark) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RuneBenchmarkList) DeepCopyInto(out *RuneBenchmarkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuneBenchmark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RuneBenchmarkList) DeepCopy() *RuneBenchmarkList {
	if in == nil {
		return nil
	}
	out := new(RuneBenchmarkList)
	in.DeepCopyInto(out)
	return out
}

func (in *RuneBenchmarkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RuneBenchmarkStatus) DeepCopyInto(out *RuneBenchmarkStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	in.LastRun.DeepCopyInto(&out.LastRun)
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]RunRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RunRecord) DeepCopyInto(out *RunRecord) {
	*out = *in
	in.SubmittedAt.DeepCopyInto(&out.SubmittedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}

func (in *RuneBenchmarkSpec) DeepCopyInto(out *RuneBenchmarkSpec) {
	*out = *in
	if in.Provisioning != nil {
		in, out := &in.Provisioning, &out.Provisioning
		*out = new(Provisioning)
		(*in).DeepCopyInto(*out)
	}
	if in.InfrastructureRef != nil {
		in, out := &in.InfrastructureRef, &out.InfrastructureRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.Budget.MaxCostUSD != nil {
		in, out := &in.Budget.MaxCostUSD, &out.Budget.MaxCostUSD
		x := (*in).DeepCopy()
		*out = &x
	}
}

func (in *RuneBenchmarkSpec) DeepCopy() *RuneBenchmarkSpec {
	if in == nil {
		return nil
	}
	out := new(RuneBenchmarkSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *Provisioning) DeepCopyInto(out *Provisioning) {
	*out = *in
	if in.VastAI != nil {
		in, out := &in.VastAI, &out.VastAI
		*out = new(VastAIProvisioning)
		**out = **in
	}
}

func (in *VastAIProvisioning) DeepCopyInto(out *VastAIProvisioning) {
	*out = *in
}
