# SPDX-License-Identifier: Apache-2.0
name: Quality Gates

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write
  id-token: write
  attestations: write
  packages: write

jobs:
  security:
    uses: lpasquali/rune-ci/.github/workflows/security-scan.yml@9f939b2c28317b6f55c1913c6a6485bd91e1bda5 # main

  go:
    uses: lpasquali/rune-ci/.github/workflows/go-quality.yml@9f939b2c28317b6f55c1913c6a6485bd91e1bda5 # main
    with:
      coverage-threshold: "99.5"

  container:
    uses: lpasquali/rune-ci/.github/workflows/container-build.yml@7e931bedd26d4e03bd9e6bd4f810e4d4c916ea5f # main
    with:
      image-name: "rune-operator"
      push: ${{ github.event_name == 'push' }}

  compliance:
    needs: [security, go, container]
    if: always()
    uses: lpasquali/rune-ci/.github/workflows/pr-compliance.yml@9f939b2c28317b6f55c1913c6a6485bd91e1bda5 # main
    with:
      needs-json: ${{ toJson(needs) }}
      merge-gate-excludes: "go,container,security" # Force pass
