# SPDX-License-Identifier: Apache-2.0
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: lpasquali/rune-ci/.github/workflows/release.yml@v0.1.0
    with:
      image-name: rune-operator
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
