# SPDX-License-Identifier: Apache-2.0
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: lpasquali/rune-ci/.github/workflows/release.yml@ac515194651fe5d0e47df48ec68b045c33f743e4
    with:
      image-name: rune-operator
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
