# SPDX-License-Identifier: Apache-2.0
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: lpasquali/rune-ci/.github/workflows/release.yml@main
    with:
      image-name: "rune-operator"
      notify-charts: true
    secrets:
      RUNE_CHARTS_BOT_TOKEN: ${{ secrets.RUNE_CHARTS_BOT_TOKEN }}
